from tkinter import *
def jia1():
	a = eval(inp1.get())
	b = eval(inp2.get())
	s = "{:.2f}+{:.2f}={:.2f}\n".format(a,b,a+b)
	txt.insert(END, s)
	inp1.delete(O,END)
	inp2.delete(O,END)
def jian1():
	a = eval(inp1.get())
	b = eval(inp2.get())
	s = "{:.2f}-{:.2f}={:.2f}\n".format(a,b,a-b)
	txt.insert(END, s)
	inp1.delete(O,END)
	inp2.delete(O,END)
def chen1():
	a = eval(inp1.get())
	b = eval(inp2.get())
	s = "{:.2f}*{:.2f}={:.2f}\n".format(a,b,a*b)
	txt.insert(END, s)
	inp1.delete(O,END)
	inp2.delete(O,END)
def chu1():
	a = eval(inp1.get())
	b = eval(inp2.get())
	s = "{:.2f}/{:.2f}={:.2f}\n".format(a,b,a/b)
	txt.insert(END, s)
	inp1.delete(O,END)
	inp2.delete(O,END)
root = Tk()
root.title("计算器")
root.geometry("500x500")
lb1 = Label(root, text="请输入两个数，按下面按钮进行计算")
lb1.pack()
inp1 = Entry(root)
inp1.pack()
inp2 = Entry(root)
inp2.pack()
btn1 = Button(root, text="加法",command = jia1)
btn1.pack()
btn2 = Button(root, text="减法",command = jian1)
btn2.pack()
btn3 = Button(root, text="乘法",command = chen1)
btn3.pack()
btn4 = Button(root, text="除法",command = chu1)
btn4.pack()
txt = Text(root)
txt.pack()
root.mainloop()
